config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews, only: [:new, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, :phone_number, :address, :category, presence: true
  validates :category, inclusion: { in: %w(chinese italian japanese french belgian), message: "%{value} is not a valid category"}
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, :rating,  presence: true
  validates :rating, inclusion: { in: (0..5).to_a, message: "%{value} is not a rating from 1 to 5"}, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy, :chef]

  # GET /restaurants
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1
  def show;end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit;end

  # POST /restaurants
  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      redirect_to @restaurant, notice: 'Restaurant was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /restaurants/1
  def update
    if @restaurant.update(restaurant_params)
      redirect_to @restaurant, notice: 'Restaurant was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /restaurants/1
  def destroy
    @restaurant.destroy
    redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :phone_number, :category)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, except: :destroy

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to restaurant_review_path(@review.restaurant)
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content,:rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :phone_number %>
    <%= f.input :category %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <h1>Restaurants</h1>
  <table>

    <thead>
      <tr>
        <th class="bg-primary bg-opacity-10">Name</th>
        <th class="bg-primary bg-opacity-10">Address</th>
        <th class="bg-primary bg-opacity-10">Options</th>
        <th class="bg-primary bg-opacity-10" colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @restaurants.each do |restaurant| %>
        <tr>
          <td class="p-2 border-end"><%= restaurant.name %></td>
          <td class="p-2 border-end"><%= restaurant.category %></td>
          <td class="p-2"><%= link_to 'Show', restaurant %></td>
          <td class="p-2"><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
          <!--td class="p-2"><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td-->
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  <%= link_to 'New Restaurant', new_restaurant_path %>
</div>

app/views/restaurants/new.html.erb
<div class="container">
  <h1>New Restaurant</h1>

  <%= render 'form', restaurant: @restaurant %>

  <%= link_to 'Back', restaurants_path %>
</div>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <h2>
    <strong>Name:</strong>
    <%= @restaurant.name %>
  </h2>

  <h3>
    <strong>Category:</strong>
    <%= @restaurant.category %>
  </h3>

  <p>
    <strong>Address:</strong>
    <%= @restaurant.address %>
    <strong>Number:</strong>
    <%= @restaurant.phone_number %>
  </p>

  <%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
  <%= link_to 'Back', restaurants_path %> |
  <%= link_to 'Leave a review', new_restaurant_review_path(@restaurant) %>

  <table>
    <thead>
      <tr>
        <th class="bg-primary bg-opacity-10">Content</th>
        <th class="bg-primary bg-opacity-10">Rating</th>
      </tr>
    </thead>

    <tbody>
    <% @restaurant.reviews.each do |review| %>
          <tr class="p-2 border-bottom">
            <td class="p-2 border-end"><%= review.content  %></td>
            <td class="p-2 border-end"><%= review.rating  %></td>
            <!--td class="p-2"><%= link_to 'Delete', restaurant_review_path(review), method: :delete, data: { confirm: "Wait what?" } %></td-->
          </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/reviews/new.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
    <%= f.input :content %>
    <%= f.input :rating %>
    <%= f.submit %>
<% end %>